spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3310/speedit?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: speedit1234
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update # create :  Re-create at the time the application runs
      show-sql: false
    properties:
      hibernate.format_sql: false
      hibernate.default_batch_fetch_size: 1000
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookplate8@gmail.com
    password: rzdjrphmdprnjqkj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379

cloud:
  aws:
    credentials:
      accessKey: AKIAZWOLNXRCMWEK3IHB       # AWS IAM AccessKey 적기
      secretKey: e17ZyGq1j5BSjmrYAIPVzhhDOpOTEO9b4jLpJcdb   # AWS IAM SecretKey 적기
    s3:
      bucket: bookplate
      dir: /speedit
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    org.hibernate.SQL: debug  #You can see all the sql that hibernate produces. Output via logger
    #org.hibernate.type: trace #You can see type of values p6py

server:
  port: 5325